{
 "title": "Internet Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoints",
    "label": "Endpoint",
    "query": {
     "query": "label_values(ping_average_response_ms,url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Ping Time to $Endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "Endpoints",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=~\"$Endpoints\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical Ping Times for $Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "Endpoints",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=~\"$Endpoints\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of Packets Lost to $Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "Endpoints",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ping_percent_packet_loss{url=~\"$Endpoints\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ping_packets_transmitted{url=~\"$Endpoints\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "timeseries",
   "description": "A graph showing download speeds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "internet_speed_download", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "description": "A graph showing upload speeds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "internet_speed_upload", "legendFormat": "__auto" }
   ]
  }
 ]
}